"""
Statistics for the objects the suite computes, as text or as LaTeX.

The interesting objects here -- the multidegree ``Q_d``, the chamber numerator,
the Laurent expansion -- are far too large to print, but their *shape* is
informative: how many terms, how sparse, how large the coefficients grow, how
much cancellation the positivity statement is asking for.  These summaries are
what actually convey the difficulty of each order.
"""

from tabulate import tabulate

from typing import Dict, Iterable, List, Optional, Sequence, Tuple

from .polynomial import Poly, negative_terms, total_degree

#: Every order with a shipped artifact.
ALL_ORDERS = (1, 2, 3, 4, 5, 6, 7)


def table(
    rows: Sequence[Sequence[object]],
    headers: Sequence[str] = (),
    align: Optional[str] = None,
) -> str:
    """
    Render rows as a fixed-width table.

    ``align`` is one character per column, ``"l"`` or ``"r"``; omitted, tabulate
    right-aligns numeric columns so magnitudes line up.
    """
    body = [[("" if cell is None else cell) for cell in row] for row in rows]
    kwargs = {}
    if align:
        kwargs["colalign"] = tuple("right" if a == "r" else "left" for a in align)
    return tabulate(body, headers=list(headers), tablefmt="simple", **kwargs)


#: booktabs rules, which tabulate only emits from the format that also escapes
#: every underscore and dollar in a cell.  We need the raw format for the maths,
#: so the rules are substituted afterwards.
_RULES = ("\\toprule", "\\midrule", "\\bottomrule")


def latex_table(
    rows: Sequence[Sequence[object]],
    headers: Sequence[str],
    caption: str,
    label: str,
    align: Optional[str] = None,
    small: bool = False,
) -> str:
    """
    The same rows as a booktabs ``tabularx``, for inclusion in the report.

    Generated rather than transcribed: the counts in these tables move whenever
    the pipeline changes, and a hand-copied table drifts silently. Cells are
    passed through verbatim, so they may contain maths.
    """
    body = [[("" if cell is None else cell) for cell in row] for row in rows]
    kwargs = {}
    if align:
        kwargs["colalign"] = tuple("right" if a == "r" else "left" for a in align)
    rendered = tabulate(body, headers=list(headers), tablefmt="latex_raw", **kwargs)

    lines = rendered.splitlines()[1:-1]  # drop tabulate's own tabular wrapper
    rules = iter(_RULES)
    lines = [next(rules, "\\midrule") if line.strip() == "\\hline" else line for line in lines]

    columns = "L" + "r" * (len(headers) - 1)
    return "\n".join(
        [
            "% Generated by tools/render_tables.py -- do not edit by hand.",
            "\\begin{table}[ht]",
            "\\centering",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            *(["\\small"] if small else []),
            f"\\begin{{tabularx}}{{\\textwidth}}{{@{{}}{columns}@{{}}}}",
            *lines,
            "\\end{tabularx}",
            "\\end{table}",
        ]
    )


def polynomial_stats(p: Poly) -> Dict[str, object]:
    """Shape summary of a polynomial: size, degree, sign split, coefficient range."""
    if not p:
        return {
            "terms": 0,
            "degree": 0,
            "negative": 0,
            "min_coeff": 0,
            "max_coeff": 0,
            "max_abs": 0,
        }
    coefficients = list(p.values())
    return {
        "terms": len(p),
        "degree": total_degree(p),
        "negative": len(negative_terms(p)),
        "min_coeff": min(coefficients),
        "max_coeff": max(coefficients),
        "max_abs": max(abs(c) for c in coefficients),
    }


def algebra_report(orders: Iterable[int] = ALL_ORDERS) -> str:
    """
    A table of the mined chamber algebras: how big each object actually is.

    ``deg Q_d`` is the codimension of the orbit closure, forced by homogeneity
    of the residue formula.  The numerator's negative-term count is a direct
    measure of how much cancellation the positivity statements ask for.

    The Vandermonde column is ``d!`` at every order, and structurally so: it is a
    Weyl denominator, so the ``2^binom(d,2)`` products of ``1 - z_m/z_l`` collapse
    to a sum over the symmetric group.
    """
    from math import comb

    from .artifacts import load_algebra

    rows: List[List[object]] = []
    for order in orders:
        algebra = load_algebra(order)
        multidegree = polynomial_stats(algebra.multidegree)
        numerator = polynomial_stats(algebra.numerator)
        rows.append(
            [
                f"A_{order}",
                algebra.nvars,
                len(algebra.denominator_factors),
                len(algebra.denominator_factors) - comb(order, 2),
                multidegree["terms"],
                multidegree["max_abs"],
                len(algebra.vandermonde),
                numerator["terms"],
                numerator["degree"],
                numerator["negative"],
                f"{100 * numerator['negative'] / numerator['terms']:.0f}%" if numerator["terms"] else "-",
                numerator["max_abs"],
            ]
        )
    return table(
        rows,
        headers=[
            "",
            "vars",
            "dim N_d",
            "deg Q_d",
            "Q_d terms",
            "max |Q_d|",
            "Vand terms",
            "N_d terms",
            "deg N_d",
            "N_d neg",
            "neg %",
            "max |coeff|",
        ],
    )


def series_report(orders: Iterable[int] = (4, 5, 6, 7), max_deg: int = 10) -> str:
    """
    A table of the chamber series: how the negative Laurent coefficients behave.

    Strong Laurent positivity is the claim that the ``negative`` column is zero;
    it holds at ``d = 4`` and fails from ``d = 5``.
    """
    from .chamber import chamber_series, sorted_negatives

    rows: List[List[object]] = []
    for order in orders:
        series = chamber_series(order, max_deg)
        negatives = sorted_negatives(series)
        rows.append(
            [
                f"A_{order}",
                len(series),
                len(negatives),
                negatives[0][0] if negatives else "--",
                sum(negatives[0][0]) if negatives else "--",
                min((c for _, c in negatives), default="--"),
                len([b for b, _ in negatives if b[0] == 0]),
            ]
        )
    return table(
        rows,
        headers=[
            "",
            f"terms (deg<={max_deg})",
            "negative",
            "first negative",
            "its degree",
            "most negative",
            "with i=0",
        ],
    )


def geometry_report(orders: Iterable[int] = ALL_ORDERS) -> str:
    """
    Invariants of the orbit closure itself, from the geometry artifacts.

    The degree is computed three independent ways when the artifact is written
    -- as ``Q_d(1, ..., 1)``, from the Hilbert series, and as the sum of the
    component multiplicities -- so a row here is three agreeing computations.

    The component count is the one column that is *not* an invariant: it belongs
    to the Groebner degeneration, and a different term order gives a different
    one summing to the same class.
    """
    from .artifacts import load_geometry

    rows: List[List[object]] = []
    for order in orders:
        geometry = load_geometry(order)
        multiplicities = [m for _, m in geometry.components]
        degrees = sorted(total_degree(f) for f, m in geometry.factors for _ in range(m))
        rows.append(
            [
                f"A_{order}",
                geometry.ambient_dimension,
                geometry.dimension,
                geometry.codimension,
                geometry.degree,
                len(geometry.components),
                f"{min(multiplicities)}-{max(multiplicities)}" if multiplicities else "-",
                len(geometry.hilbert_numerator) - 1,
                (
                    ("x".join(str(e) for e in degrees) if len(degrees) > 1 else "irreducible")
                    if degrees
                    else "Q_d = 1"
                ),
            ]
        )
    return table(
        rows,
        headers=[
            "",
            "dim N_d",
            "dim O_d",
            "codim",
            "deg O_d",
            "components",
            "mult",
            "deg Hilb",
            "Q_d factors",
        ],
    )


def cancellation_report(orders: Iterable[Tuple[int, int]] = ((4, 12), (5, 12), (6, 10), (7, 10))) -> str:
    """
    How much cancellation the weak conjecture actually asks for.

    Strong Laurent positivity fails from ``d = 5``, so some ``A_beta`` are
    negative; the weak conjecture survives because each Chern coefficient sums
    many of them.  This measures the gap between the two: how many coefficients
    are negative, how negative they get, and what fraction of the positive mass
    they represent.  The answer is that the negative part is very small and very
    flat, which is what makes a bound on it look like a plausible route.
    """
    from .chamber import chamber_series
    from .chern import chern_coefficients

    rows: List[List[object]] = []
    for order, cap in orders:
        series = chamber_series(order, cap)
        negatives = [v for v in series.values() if v < 0]
        positive_mass = sum(v for v in series.values() if v > 0)
        negative_mass = -sum(negatives)
        _, chern = chern_coefficients(order, l_max=0)
        rows.append(
            [
                f"A_{order}",
                cap,
                len(series),
                len(negatives),
                f"{100 * len(negatives) / len(series):.1f}%",
                min(negatives) if negatives else "-",
                negative_mass,
                f"{100 * negative_mass / positive_mass:.2f}%",
                len(chern),
                min(chern.values()),
            ]
        )
    return table(
        rows,
        headers=[
            "",
            "deg <=",
            "A_beta",
            "negative",
            "%",
            "least",
            "neg mass",
            "of pos",
            "C(M) at l=0",
            "min C(M)",
        ],
    )
