"""
Combinatorics of monomial ideals, used to read a multidegree off an initial ideal.

The initial ideal of a Gröbner basis is monomial, and for a monomial ideal both
halves of the multidegree computation are combinatorial rather than algebraic:
its minimal primes are generated by variables, and localising at one of them is a
restriction of exponent vectors.  Doing that here rather than through a
general-purpose primary decomposition is what brings ``Q_7`` into reach --- about
41 s of Singular against a few tenths of a second.

The *length* of a localised component is left to Sage.  Counting standard
monomials by hand is a short function and an easy one to get subtly wrong, and an
undercount here would not look like a bug: it would look like a different
multidegree, which is to say like mathematics.

Deliberately free of any Sage import, so the arguments most likely to hide an
off-by-one can be tested in the ordinary virtualenv.
"""

from typing import FrozenSet, Iterable, List, Sequence, Tuple

Exponents = Tuple[int, ...]


def minimal_transversals(supports: Iterable[FrozenSet[int]], bound: int) -> List[FrozenSet[int]]:
    """
    Minimal primes of a monomial ideal, as index sets, up to codimension ``bound``.

    ``P_S = (x_i : i in S)`` contains a monomial ideal exactly when ``S`` meets
    the support of every generator, so the minimal primes are the minimal
    *transversals* of the supports.

    Partial transversals larger than ``bound`` are discarded as they appear.
    That is sound because every subset of a transversal of size ``<= bound`` is
    itself of size ``<= bound``, so nothing of that size is pruned; and it keeps
    a codimension check against ``bound`` honest in both directions, since a
    component of codimension *below* ``bound`` would still be found.

    Returns the transversals sorted by size, smallest first.
    """
    if bound < 0:
        raise ValueError(f"bound must be nonnegative, got {bound}")

    antichain = {frozenset()}
    # Smallest supports first: they branch least and constrain most.
    for support in sorted(supports, key=len):
        if not support:
            # An empty support cannot be hit, so the ideal contains a unit and
            # has no minimal primes at all.
            return []
        grown = set()
        for partial in antichain:
            if partial & support:
                grown.add(partial)
                continue
            for index in support:
                extended = partial | {index}
                if len(extended) <= bound:
                    grown.add(extended)
        antichain = _minimal_elements(grown)
    return sorted(antichain, key=lambda s: (len(s), sorted(s)))


def _minimal_elements(sets: Iterable[FrozenSet[int]]) -> set:
    """Keep only the elements containing no other; a superset is never minimal."""
    kept: List[FrozenSet[int]] = []
    for candidate in sorted(sets, key=len):
        if not any(other <= candidate for other in kept):
            kept.append(candidate)
    return set(kept)


def restrict_generators(exponents: Sequence[Exponents], indices: Sequence[int]) -> Tuple[Exponents, ...]:
    """
    Generators of a monomial ideal localised at the prime on ``indices``.

    Setting every other variable to 1 restricts each exponent vector to
    ``indices``.  A generator restricting to zero would mean the localised ideal
    is the unit ideal; that cannot happen for a prime containing the ideal, since
    every generator's support then meets ``indices``, and such a generator is
    dropped rather than silently producing a nonsense length.

    Generators divisible by another are removed, so the result is the minimal
    generating set and can be used as a cache key.
    """
    restricted = set()
    for monomial in exponents:
        image = tuple(monomial[i] for i in indices)
        if any(image):
            restricted.add(image)
    return tuple(
        sorted(
            image
            for image in restricted
            if not any(other != image and all(a <= b for a, b in zip(other, image)) for other in restricted)
        )
    )
