"""
Extreme rays and facets of the cone C_2 (products of Schur functions with at most two
rows) in each degree n, computed with normaliz.  Records whether C_2 is simplicial,
i.e. generated by a basis as C_1 is by the Chern monomials.

    python tools/c2_cone.py 10 results/c2_cone.json      (needs the normaliz binary)
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from chernpp import corank


def partitions(n, top=None):
    top = n if top is None else top
    if n == 0:
        yield ()
        return
    for k in range(min(n, top), 0, -1):
        for rest in partitions(n - k, k):
            yield (k,) + rest


def products(n, r):
    parts = [p for m in range(1, n + 1) for p in partitions(m) if len(p) <= r]
    out = set()

    def rec(rem, start, acc):
        if rem == 0:
            out.add(tuple(acc))
            return
        for i in range(start, len(parts)):
            if sum(parts[i]) <= rem:
                rec(rem - sum(parts[i]), i, acc + [parts[i]])

    rec(n, 0, [])
    return sorted(out)


def block(lines, key):
    i = next(k for k, line in enumerate(lines) if re.fullmatch(r"\d+ " + key + ":", line.strip()))
    m = int(lines[i].split()[0])
    return [list(map(int, lines[i + 1 + j].split())) for j in range(m)]


def cone(n, r=2):
    P = list(partitions(n))
    by_vector = {}
    for factors in products(n, r):
        g = corank.schur_product(list(factors))
        by_vector.setdefault(tuple(g.get(p, 0) for p in P), []).append(factors)
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "c.in"
        src.write_text(
            f"amb_space {len(P)}\ncone {len(by_vector)}\n"
            + "".join(" ".join(map(str, v)) + "\n" for v in sorted(by_vector))
            + "SupportHyperplanes\nExtremeRays\n"
        )
        subprocess.run(["normaliz", "-c", str(src)], check=True, capture_output=True)
        lines = (Path(tmp) / "c.out").read_text().splitlines()
    rays, facets = block(lines, "extreme rays"), block(lines, "support hyperplanes")
    named = []
    for ray in rays:
        top = max(ray)
        match = next(
            f for v, f in by_vector.items() if any(v) and all(a * top == b * max(v) for a, b in zip(v, ray))
        )
        named.append([list(map(list, match[0]))])
    return {
        "n": n,
        "dimension": len(P),
        "extreme_rays": len(rays),
        "facets": len(facets),
        "simplicial": len(rays) == len(P),
        "rays": named,
    }


def main(top, path):
    rows = []
    for n in range(2, top + 1):
        row = cone(n)
        rows.append(row)
        print({k: v for k, v in row.items() if k != "rays"}, flush=True)
    Path(path).write_text(json.dumps(rows, indent=1))


if __name__ == "__main__":
    main(int(sys.argv[1]), sys.argv[2])
