"""
Render the tables of ``report/morin_d7.tex`` from ``results/*.json``.

    python tools/render_d7_tables.py report/tables
"""

import json
import sys
from collections import defaultdict
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
HEADER = "% Generated by tools/render_d7_tables.py -- do not edit by hand.\n"


def rho(row):
    ranks = [int(r) for r, v in row["memberships"].items() if v]
    return min(ranks) if ranks else None


def corank_table():
    rows = [r for r in json.loads((RESULTS / "corank_survey.json").read_text()) if "memberships" in r]
    by = defaultdict(dict)
    meta = {}
    for r in rows:
        by[r["singularity"]][r["relative_dimension"]] = rho(r)
        meta[r["singularity"]] = r["support_corank"]
    ls = sorted({l for v in by.values() for l in v})

    def key(name):
        fam = name.split("_")[0]
        return ({"I": 0, "III": 1}.get(fam, 2), fam, name)

    lines = [
        HEADER,
        "\\begin{longtable}{@{}l" + "c" * (len(ls) + 1) + "@{}}\n",
        "\\caption{$\\rho(\\Tp) = \\min\\{r : \\Tp \\in C_r\\}$ on the non-Morin tables of the registry, by relative "
        "dimension $\\ell$, with the support corank $s$ (every Schur component contains $(\\ell+s)^s$). Every entry "
        "is decided with an exact certificate; a dash means not in the registry or not yet surveyed.}"
        "\\label{tab:rho}\\\\\n",
        "\\toprule\n",
        "singularity & $s$ & " + " & ".join(f"$\\ell={l}$" for l in ls) + " \\\\\n",
        "\\midrule\n\\endhead\n",
    ]
    for name in sorted(by, key=key):
        if name.startswith("cup"):
            label = "$\\Sigma^3$ open (cup)"
        elif name.startswith("("):
            label = "$" + name.replace("^", "^") + "$"
        else:
            fam, idx = name.split("_", 1)
            label = f"$\\mathrm{{{fam}}}_{{{idx}}}$"
        cells = []
        for l in ls:
            v = by[name].get(l)
            s = meta[name]
            cells.append("---" if v is None else (f"\\textbf{{{v}}}" if v > s else str(v)))
        lines.append(f"{label} & {meta[name]} & " + " & ".join(cells) + " \\\\\n")
    lines.append("\\bottomrule\n\\end{longtable}\n")
    return "".join(lines)


def anatomy_table():
    lines = [
        HEADER,
        "\\begin{table}[ht]\n\\centering\n",
        "\\caption{Charge layers $\\max M = p$ (every packet complete). $N(M)$ is the negative mass of the packet and "
        "$A_{\\mathrm{dom}}$ the coefficient of its decreasing ordering $\\beta_{\\max}(M)$.}\n\\label{tab:anatomy}\n",
        "\\begin{tabular}{@{}rrrrrrr@{}}\n\\toprule\n",
        "$d$ & $p$ & packets & with $A_\\beta<0$ & $\\min C(M)$ & $\\min A_\\beta$ & $\\max N(M)/A_{\\mathrm{dom}}$ \\\\\n\\midrule\n",
    ]
    for d in (5, 6, 7):
        data = json.loads((RESULTS / f"anatomy_a{d}.json").read_text())["layers"]
        for p, layer in sorted(data.items(), key=lambda kv: int(kv[0])):
            neg = [r for r in layer["packets"] if r["negative"]]
            q = max((Fraction(r["negative_mass"], r["dominant"]) for r in neg), default=Fraction(0))
            s = layer["summary"]
            qs = (
                "0"
                if q == 0
                else (f"{q.numerator}/{q.denominator}" if q.denominator < 1000 else f"{float(q):.1e}")
            )
            lines.append(
                f"{d} & {p} & {s['packets']} & {s['with_negatives']} & {s['min_chern']} & {s['min_A']} & ${qs}$ \\\\\n"
            )
        lines.append("\\midrule\n" if d < 7 else "")
    lines.append("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return "".join(lines)


def landscape_table():
    rows = json.loads((RESULTS / "hecke_landscape.json").read_text())
    lines = [
        HEADER,
        "\\begin{table}[ht]\n\\centering\n",
        "\\caption{The 0-Hecke positivity set $P_d$ restricted to the packets complete in the level box $\\min M \\ge -L$.}\n"
        "\\label{tab:landscape}\n\\begin{tabular}{@{}rrrrrr@{}}\n\\toprule\n",
        "$d$ & $L$ & packets & with $A_\\beta<0$ & $|P_d|$ & minimal elements \\\\\n\\midrule\n",
    ]
    for r in sorted(rows, key=lambda r: (r["d"], r["level"])):
        lines.append(
            f"{r['d']} & {r['level']} & {r['packets']} & {r['negative_packets']} & "
            f"{r['positive_set_size']} & {len(r['minimal'])} \\\\\n"
        )
    lines.append("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return "".join(lines)


def main(out):
    out = Path(out)
    (out / "corank.tex").write_text(corank_table())
    (out / "anatomy.tex").write_text(anatomy_table())
    (out / "landscape.tex").write_text(landscape_table())


if __name__ == "__main__":
    main(sys.argv[1])
